CREATE TABLE thingful_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    article_id INTEGER
        REFERENCES thingful_articles(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES thingful_users(id) ON DELETE CASCADE NOT NULL
);